
FROM docker.elastic.co/logstash/logstash:6.2.4
COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY logstash.conf /usr/share/logstash/config/logstash.conf
#COPY sample.log /var/log/sample.log
