apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kibana
    spec:
      containers:
      - image: 870594606895.dkr.ecr.eu-west-2.amazonaws.com/sre-kibana
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
---
