apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sre-elk-kibana
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: sre-elk-kibana
    spec:
      containers:
      - image: 870594606895.dkr.ecr.eu-west-2.amazonaws.com/sre-kibana
        name: sre-elk-kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
---
