apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: logstash-elasticsearch
  labels:
    k8s-app: logstash-logging
spec:
  selector:
    matchLabels:
      name: logstash-elasticsearch
  template:
    metadata:
      labels:
        name: logstash-elasticsearch
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: logstash-elasticsearch
        image: 870594606895.dkr.ecr.eu-west-2.amazonaws.com/sre-logstash
#        resources:
#          limits:
#            memory: 200Mi
#          requests:
#            cpu: 100m
#            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      nodeSelector:
        role: node
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
