apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: sre-elk-logstash
  labels:
    k8s-app: sre-elk-logstash
spec:
  selector:
    matchLabels:
      name: sre-elk-logstash
  template:
    metadata:
      labels:
        name: sre-elk-logstash
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: sre-elk-logstash
        image: 870594606895.dkr.ecr.eu-west-2.amazonaws.com/sre-logstash
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      nodeSelector:
        role: node
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
